### ISSUE TITLE
Saved Cart feature styles re-import whole spartacus styles

### ISSUE THREAD

**Issue by mateuszo** [SAP/spartacus#12714]
The saved cart feature library styles import the whole `@spartacus/styles` library. Schematics add feature library styles import after global styles (`styles.scss`). Because of this, customizations (e.g. changes to css variables or `$skipComponentStyles`) in `styles.scss` are being overwritten. 

- Library version: 3.3

**To Reproduce**
1. Install Spartacus using schematics
2. Install Saved cart feature using schematics
3. Add some customizations in `styles.scss` eg.:
```scss 
$skipComponentStyles: (cx-mini-cart);
@import "~@spartacus/styles/index";

:root {
  --cx-color-primary: #1900ff;
}
```
4. Observe that the changes did not take effect

**Expected behavior**
Customizations done to `styles.scss` should take effect. Feature libraries should not re-import `@spartacus/styles`.
