### ISSUE TITLE
Introduce style versioning to avoid breaking changes during minors

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#7426]
Calydon theme has now been set-as-base for **2.0**, its previous structure is available for the next theme, therefore we need to:

- [x] Choose a name or number for the next theme
- [ ] Test it out with one of the 2.x tickets on the Praetorians' board.

**Comment by tobi-or-not-tobi** [comment]
Closing, as we fixed this with #7956

**Comment by tobi-or-not-tobi** [comment]
QA:
Introduce version specific styles in an existing component, i.e. `_mini-cart.scss`:
```scss
    @include forVersion(1.5) {
      background: green;
    }

    @include forVersion(2.1) {
      background: blue;
    }

    @include forVersion(2.2) {
      background: red;
    }
```

Play with the version variables, to opt-in to specific version: 
- use `$useLatestStyles: true;` in the `styles.scss` to receive latest styles (background should be green)
- drop `$useLatestStyles: true;` or change it to `false` to fallback to latest stable styles (which is 2.0, so background should be red)
- add `$styleVersion:2.1` to opt-in to 2.1. styling, background should be blue.
- add `$styleVersion:2.2` to opt-in to 2.2. styling, background should be green.
